language: clojure
script: lein doo node "tests" once
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
  email: false
before_install:
- sudo add-apt-repository --yes ppa:ethereum/ethereum
- sudo apt-get -qq update
before_script:
- echo 'Installing Solc'
- sudo wget --no-check-certificate -P /bin https://github.com/ethereum/solidity/releases/download/v0.4.24/solc-static-linux
- sudo chmod a+x /bin/solc-static-linux
- sudo ln -s /bin/solc-static-linux /usr/bin/solc
- echo 'Compiling contracts'
- lein solc once
- echo 'Installing Ganache'
- npm install -g ganache-cli
- echo 'Running Ganache instance with auto mining'
- ganache-cli -p 8548 > /dev/null &
- echo 'Running Ganache without auto mining'
- ganache-cli -p 8549 -b 3 > /dev/null &
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git remote rm origin
- git remote add origin https://${GH_TOKEN}@github.com/district0x/district-ui-logging.git > /dev/null 2>&1
env:
  global:
  - secure: tFVOVNGXcPs680MkzH3dw8AtDnwSdOZz1EQLaNietr8jqaiBsjN8dJ5CuC1Q46SfLZHrP8RlscBYgxELebg94GrkOCbl8CYE6fTPlgrA63rkVOTzAr6RTBf4HewUDmQlEGxOLYrnfEbaeeS/2JBwuSjfD5MI3lBXD1wcHdkLNyL97WhYpZ1wh7/d9kG2Q04IXl4Axzu0rAE4K020kkSZPza35+5Xtglu+EkL4yjeun9vNtpvGOe66s2+fQtqZpnBDjYsQsuLdctblICbckhhrT4oxnMO6Eqk9IEvIRxZSeOxed7O8H78CCDHYXjZDB+ZZMppoQf0mvio3nYlNW0ZGlFmLfql6erAYVTqTtef80PG1BhZQYFHzvYYC0UOKLBsIioxAwu0EfdlD2ei+ZwevWsDsyIpYyfOmwK0B5HnxCGSUgFhuqMroWDY3PY+sZMB7AuVcCSxSG49wsrfFRUwUmZMMB1zLVmZbQOlY/JaROoZlnuvWxVa7EwbxXyErLUIWB6i8ECw8KZBedaJdMf2MUdV3ipm3/X5WEqGz/qcievJWQGwVrbOdJU1lDoOH4JFEp7tag3yzUf0BlmqX5uzDZnIr1VyKAY0Hl/S7UBdNCx6GrY1bFlj91ZuwciQHIxjqpy2yzi5Dh6xjmFZWAL5ucqHl2pytQOsMPuqR8gBcPc=
  - secure: uIfDNkahJ3khYu2zZ3e6wRrQD/oKEeX2P/dufTCoxYsFeFIBNJGAHvaRL506wF668cEXX0lkMi7xIPr8GsVgOlK0Q/8P+rg+q6Vm18rTNMxbwSSy5x8EVDV4JitRkyuFMkW+sn65YhGZKQAkNGkHsnY3fIR8RdrMYxHCpcl56B3IqF75wlYzo+f6oFnBoxp8mad8MGdTsNHNsxTTAMotTrcKusX9TrcwmtdbJZj05NGMLr71iwMRcss3d4rbGcThVlc/8tdLr/695MWA76MPNA371vm4oiZt+yFAgLQYPN/e2ujvjLGsbzZ+nbcvUexDhfo2IiCefzrIx/z+9mHByRTRFxHxv+LfeWyDSiuS72+UZ53duT4W5X9uLYTK1ISvRjx9Ui7TuwYPnMBwMR25UH+GncCxycemaMxyRmOd9VNyVhj2MXBfxlmZ5W6WPVwSd4DOpeDVrD/TDMuSqZt4yw7zb/XaT/sWSKFRh5EVtHTzVAqZDiuij6JbJeAODEfKMnjEs4XRrXarVnV+8inh6W1epAP7esg2yn/W/+wPHf1zSKHukrAHLmQhH1hUz6pRONtT6bMQHm26IiWQwMbBiu4MC3j6NxPDU+9o5xF1o+potapMA+q8PgTbTDc2ULob5aJAfnXjJKauNBQUpE+hqjTI0wajSRWze++PPh481BA=
  - secure: Sb2HiWxR/wOcGABMD1ZE0fuejdLEzIAxCkpSDkdQg23ys3vbofKz0SQo4SjLGHcXvoA2VQXwN3zp8Wy9f3GUKdsBmVUokdrsMUZM59gIiVArk1/QeuF8IThHuCt4GFCP8r+mDsm27XmyXWSxCVPdF63mi4uDUr9DzAl4ThRjUUQU6Prb2nsDjBf5gecoZuztK1503QE/l6BCDzFqgDukXgQtwnv2l6/A5KEAb0Ac5t7X86zNilJVX2hMoSHPanrlU4gPH7V72gKvwha+OQ0LtiO1zn0GFOC/XYaX/ELPLxcAEj92Wz4JBXIBMWx4VhUoFvPdJjfyc3l6wbznCeTVtk+hQfslD0fv+hw4RfBuSz0sf1Z7rxsOD9EDM7q9y51k7WLQ5ulZkKxSBMWwNRmOYZ6iis9Yzbgt25Nnxmar66V2s4ODjCrQNZkvkaTSnhE7ssY84mS3zJp6pHJTi+LhZ/dBHTcp7CI5ekoo/+EfUHdaou0OLTVfn9Hdb/HE3FeCZrstdNaf3pQuuH08F+mi2up85IhKJJdmcpQcaixOfVJ11H90Qu/JR9b4i4XFhCGYNnbYb+JMPfr1p/HjW04wHJxZhpvP25Me9yGvEjODWGz1cfYVLl2Ec0h/Gkh2CLNclSJyna29t0tPrbb31qTuRIhU/DuTtUxX8fZUXoVii/I=
deploy:
- provider: script
  skip_cleanup: true
  script: lein release :patch
  on:
    branch: master
