language: clojure
script: lein doo node "tests" once
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
before_install:
 - sudo add-apt-repository --yes ppa:ethereum/ethereum
 - sudo apt-get -qq update
before_script:
  - "echo 'Installing Solc'"
  - sudo wget --no-check-certificate -P /bin https://github.com/ethereum/solidity/releases/download/v0.4.24/solc-static-linux
  - sudo chmod a+x /bin/solc-static-linux
  - sudo ln -s /bin/solc-static-linux /usr/bin/solc
  - "echo 'Compiling contracts'"
  - lein solc once
  - "echo 'Installing Ganache'"
  - npm install -g ganache-cli
  - "echo 'Running Ganache instance with auto mining'"
  - ganache-cli -p 8548 > /dev/null &
  - "echo 'Running Ganache without auto mining'"
  - ganache-cli -p 8549 -b 3 > /dev/null &
